---
kind: pipeline
name: default
# start pipe
steps:
- name: build
  image: plugins/hugo
  settings:
    hugo_version: 0.71.1
    extended: true
    pull: always
    url: https://dtx3k.github.io
    validate: true


- name: push commit
  image: appleboy/drone-git-push
  settings:
    branch: master
    remote: git@github.com:dtx3k/dtx3k.github.io.git
    force: false
    commit: true